{
 "title": "Flow Overview",
 "tags": [
  "pktvisor",
  "netflow",
  "flow"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "legendFormat": "in", "expr": "sum(flow_in_bytes)" },
    { "legendFormat": "out", "expr": "sum(flow_out_bytes)" }
   ]
  },
  {
   "title": "Collecting devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count by(device) (flow_in_bytes))"
    }
   ]
  },
  {
   "title": "Sources",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count by(ip) (flow_top_in_src_ips_bytes))"
    }
   ]
  },
  {
   "title": "Destinations (ports)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count by(port) (flow_top_in_dst_ports_bytes))"
    }
   ]
  },
  {
   "title": "Total (observed) traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(flow_in_bytes) + sum(flow_out_bytes)"
    }
   ]
  },
  { "title": "Top talkers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Top sources",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, flow_top_in_src_ips_bytes)"
    }
   ]
  },
  {
   "title": "Top destinations (by port)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, flow_top_in_dst_ports_bytes)"
    }
   ]
  },
  { "title": "Conversations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Conversation total bytes",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, flow_top_conversations_bytes)"
    }
   ]
  },
  {
   "title": "Conversation traffic over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(flow_top_conversations_bytes)"
    }
   ]
  },
  {
   "title": "Breakdown by source/destination pair",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, flow_top_conversations_bytes)"
    }
   ]
  }
 ]
}