name: unetwork udiscovery - test
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - release
    paths:
      - "orb-discovery/network-discovery/**"
      - "!orb-discovery/network-discovery/docker/**"
  pull_request:
    paths:
      - "orb-discovery/network-discovery/**"
      - "!orb-discovery/network-discovery/docker/**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    uses: ./.github/workflows/_backend-test-go.yaml
    with:
      app-name: network-discovery
